- main_test.go
An argument could be made that Prometheus should always come first.
Signed-off-by: Richard Hartmann <richih@richih.org>
> Order tests alphabetically

- remote_write/cases/summary.go
- remote_write/main_test.go
Simple test that checks summaries are scraped and propagated correctly.
Signed-off-by: Tom Wilkie <tom@grafana.com>
> Add test for summaries.

- remote_write/cases/labels.go
Its a bit harsh to fail agents on not providing the up metric in unrelated tests.  So remove that check, and use other signals.  Makes NameLabel test pass for Telegraf and Otel.
Signed-off-by: Tom Wilkie <tom@grafana.com>
> Don't require the up metric for non-up-metric tests.

- remote_write/targets/common.go
- remote_write/targets/otel.go
- remote_write/targets/vmagent.go
You can build your own vmagent for mac and stick it in the bin/ dir, and the tests won't download it.
Signed-off-by: Tom Wilkie <tom@grafana.com>
> Remove OS check for VMAgent, Update Otel version and Only download once.

- remote_write/cases/retries.go
- remote_write/main_test.go
```
--- FAIL: TestRemoteWrite (50.30s)
--- PASS: TestRemoteWrite/grafana (0.00s)
--- PASS: TestRemoteWrite/grafana/Retries400 (10.07s)
--- PASS: TestRemoteWrite/grafana/Retries500 (10.08s)
--- FAIL: TestRemoteWrite/otelcollector (0.01s)
--- PASS: TestRemoteWrite/otelcollector/Retries400 (10.02s)
--- FAIL: TestRemoteWrite/otelcollector/Retries500 (10.02s)
--- PASS: TestRemoteWrite/prometheus (0.01s)
--- PASS: TestRemoteWrite/prometheus/Retries400 (10.05s)
--- PASS: TestRemoteWrite/prometheus/Retries500 (10.10s)
--- FAIL: TestRemoteWrite/telegraf (0.01s)
--- PASS: TestRemoteWrite/telegraf/Retries400 (10.02s)
--- FAIL: TestRemoteWrite/telegraf/Retries500 (10.02s)
--- FAIL: TestRemoteWrite/vector (0.01s)
--- PASS: TestRemoteWrite/vector/Retries400 (10.03s)
--- FAIL: …
```
> Add test for retry behaviour: should retries 5xx, should not retry 4xx.

- promql/cmd/promql-compliance-tester/main.go
This was required for making AMP testing work through the AWS SigV4 proxy.
Signed-off-by: Julius Volz <julius.volz@gmail.com>
> Allow overriding the Host header

- alert_generator/specification.md
2 lines meaning the same thing, the one removed is more verbose.
> Remove duplication in the alert generation specification

- alert_generator/specification.md
Noticed this when working on the test suite.
Code references:
For `/api/v1/alerts`
https://github.com/prometheus/prometheus/blob/a961062c37f1675d5925d8b74ddda0a6322ed82d/web/api/v1/api.go#L1064
For `/api/v1/rules`
https://github.com/prometheus/prometheus/blob/a961062c37f1675d5925d8b74ddda0a6322ed82d/web/api/v1/api.go#L1242
> Update Alert-Generator spec: no inactive alerts in the GET API

- alert_generator/testsuite/cases/all_cases.go
- alert_generator/testsuite/cases/case_pending_firing_resolved.go
- alert_generator/testsuite/cases/case_pending_resolved_and_always_inactive.go
- alert_generator/testsuite/cases/case_zero_for_and_small_for.go
- alert_generator/testsuite/cases/expected_alert.go
- alert_generator/testsuite/rules.yaml
- alert_generator/testsuite/server.go
* pending alerts having changing annotation values (checked via API)
* firing alert being re-sent at expected intervals when the alert is active with changing annotation contents.
* Alert that goes directly to firing state (skipping the pending state) because of zero for duration.
* When the for duration is non-zero and less than the evaluation interval, firing alert must be sent after the second evaluation of the rule and not before.
> Add four more cases to alert generator test suite

- alert_generator/testsuite/cases/expected_alert.go
- alert_generator/testsuite/server.go
Finally, with this, the current tests are stable against a Prometheus server.
> Fix the logic of ignoring an expected alert

- alert_generator/testsuite/cases/case_pending_firing_resolved.go
- alert_generator/testsuite/cases/case_pending_resolved_and_always_inactive.go
- alert_generator/testsuite/cases/case_zero_for_and_small_for.go
- alert_generator/testsuite/cases/expected_alert.go
- alert_generator/testsuite/rules.yaml
- alert_generator/testsuite/server.go
- alert_generator/testsuite/testsuite.go
First one being rule with zero 'for' duration firing again
after inactive alert was no longer being sent.
Second being the rule with non-zero 'for' duration firing
again while inactive alert was still being sent.
> Add two cases of rule firing again after getting inactive

- alert_generator/testsuite/cases/all_cases.go
- alert_generator/testsuite/cases/case_new_alerts_and_order_check.go
- alert_generator/testsuite/cases/case_pending_resolved_and_always_inactive.go
- alert_generator/testsuite/cases/case_zero_for_and_small_for.go
- alert_generator/testsuite/rules.yaml
* Rule that produces new alerts that go from pending->firing->inactive
while already having active alerts.
* A rule group having rules which are dependent on the ALERTS series from
the rules above it in the same group.
* Expansion of template in annotations only use the labels from the query
result as source data even if those labels get overridden by the rules.
They do not use the rules' additional labels.
> [alert_generator] Add test case covering ordered rules and producing more alerts after a delay.

- alert_generator/specification.md
Turns out `safeHtml` has no effect when used in alerting rule config and HTML templates are only expanded the HTML way from console template files. Hence excluding it from compliance.
I have asked on the IRC to confirm this. But if anyone knows, feel free to comment here as well :)
> [alert_generator] Exclude another template variable from the specification

- alert_generator/specification.md
Add `lastEvaluation` field to `/api/v1/rules` specification
since it is required for tests to pass.
> alert_generator: mention `lastEvaluation` field in group's spec

- alert_generator/config/config.go
- alert_generator/remote_write.go
- alert_generator/test-amazon-managed-service-for-prometheus.yaml
- alert_generator/test-amp.yaml
- alert_generator/test-example.yaml
- alert_generator/utils.go
Adding sigv4 support to allow testing against [Amazon Managed Service for Prometheus](https://aws.amazon.com/prometheus/) easier. 
Signed-off-by: Alvin Lin <alvinlin@amazon.com>
> Add Sigv4 support to alert_generator tests

- alert_generator/README.md
- alert_generator/alert_message_parsers.go
- alert_generator/cmd/alert_generator_compliance_tester/main.go
- alert_generator/config/config.go
- alert_generator/go.mod
- alert_generator/server.go
- alert_generator/specification.md
- alert_generator/test-example.yaml
- alert_generator/test-prometheus.yaml
- alert_generator/testsuite.go
This PR adds an option to custom parse the alert payload into the Go struct that we desire.
More context in https://groups.google.com/g/prometheus-developers/c/dBbKTnaSg_4
Note: this also updates the spec to reflect the changes in the requirements of the alert payload
> [alert_generator] Allow writing custom parsers for the alert payload

- alert_generator/test-vm-vmalert.yaml
Add testing configuration for VictoriaMetrics `vmalert`
component whcih can be used as alerts generator.
`vmalert` can be configured to use `Prometheus` as remote
storage for querying alerts and writing back results.
> alert_generator: add `vmalert` config

- alert_generator/cases/expected_alert.go
We are using `2*MaxRTT` for firing alert while it was just `MaxRTT` for resolved. This PR fixes it.
> [alert_generator] Fix tolerance for matching end time of resolved alert

- promql/promql-test-queries.yml
Prometheus 2.33 started to allow negative offsets, so we need to mark queries
with negative offsets as valid now.
Signed-off-by: Julius Volz <julius.volz@gmail.com>
> Allow querying for negative offsets

- alert_generator/test-example.yaml
- alert_generator/test-promscale.yaml
This PR adds configuration for testing Promscale with TimescaleDB for alert_generator compliance in `test-promscale.yaml`.
> Adds support for Promscale in alert-generator compliance

- alert_generator/cmd/rule_config_builder/main.go
- alert_generator/config/config.go
- alert_generator/server.go
- alert_generator/utils.go
`ioutil` is deprecated from go1.16 (ref: https://go.dev/doc/go1.16#ioutil).
So removed them.
Signed-off-by: inosato <si17_21@yahoo.co.jp>
> Remove ioutil from alert_generator

- alert_generator/server.go
This PR adds the needed CORS header so that sinks like webhook.site can use the browser as a proxy to access the local network.
Prior to this PR this approach would cause errors and warnings on the client side.
> [alert_generator] Add CORS header and support for preflight check

- promql/cmd/promql-compliance-tester/main.go
When running the PromQL Compliance test, we can sometimes observe the queries with negative offset failing. The reason for this is that by default query end time is `now() - 2m`. And we have queries with negative offsets of -5m and -10m. That, generally, means that we are querying into the future for 3m for the first query (with `offset -5`), and 8m for the second query (with `offset -10`). When running the compliance test, sometimes a race condition can be observed with data ingestion where one storage still hasn't ingested the same sample that the other system already has ingested. As a result, queries with negative offsets into the future can fail since the resulting time series will have additional samples at the end (the one that the other storage system still hasn't ingested at that …
> Set offset for the query end time to -12 minutes

- remotewrite/sender/targets/otel.go
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35119
The counter was being renamed to counter_total.  Disable suffixing so that we pass the compliance test.
> Disable metric suffixing in OTel PRW exporter to pass compliance tests

- README.md
- openmetrics/README.md
Related to https://github.com/prometheus/OpenMetrics/issues/287
The OM 2.0 effort is kicked off, and will start developing on main. This updates the links to OpenMetrics to reference the 1.0 release. The OM project has also been moved into the prometheus github org.
> update links to openmetrics to reference the v1.0.0 release

- remotewrite/sender/targets/otel.go
To unblock the compliance tests in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36873
cc @dashpole
> Add fallback scrape protocol to OTel collector

- remotewrite/sender/targets/otel.go
Reverts prometheus/compliance#134
The PR solved the [compliance test for the PR that updates the dependency to 3.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/13077886194/job/36494390295?pr=36873), but breaks everywhere else. 
I'll revert this revert once we're ready to update the dependency in the collector 🫠
> Revert "Add fallback scrape protocol to OTel collector"

- promql/cmd/promql-compliance-tester/main.go
- promql/comparer/comparer.go
- promql/config/config.go
- promql/go.mod
- promql/go.sum
- promql/output/html.go
Replace archived `github.com/pkg/errors` with standard library error handling.
> Cleanup deprecated package

- remotewrite/sender/targets/otel.go
Fallback_scrape_protocol isn't needed since 1.20.1
> remotewrite/otel: Remove `fallback_scrape_protocol`

- remotewrite/sender/targets/otel.go
The [v0.123.0 release of collector core](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.123.0) has promoted a feature gate to beta that removes support for `service.telemetry.metrics.address`. As of v0.123.0 this setting does nothing unless the feature gate is disabled.
Since the collector is moving away from `service.telemetry.metrics.address` in favor of the otel sdk configuration, this PR updates the otel target to use the otel go's metrics SDK to export metrics via prometheus.
Collector contrib has a [workflow](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/workflows/prometheus-compliance-tests.yml) that is failing right now because of the breaking change, but this PR will fix it.
Closes …
> Update otel target to handle breaking change

- remotewrite/sender/targets/otel.go
In https://github.com/prometheus/compliance/pull/160 we updated the collector's config to use the OTEL SDK's prometheus exporter. We added a couple `without` config options, but these make the tests fail. 
I'm not sure why CI passed, but I can consistently get the tests to fail if these config options are included but they consistently pass if they are all removed.
Related to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39105
> [remotewrite/sender/otel] Remove additional `without` config
